server:
  port: 8080 # Puerto del Gateway

spring:
  application:
    name: gateway

  cloud:
    # Deshabilita el chequeo de versin de Spring Boot vs. Spring Cloud
    compatibility-verifier:
      enabled: false

    gateway:
      routes:
        # --- Ruta para Usuario MS ---
        - id: usuario-ms
          uri: http://localhost:8001
          predicates:
            - Path=/usuarios/**, /cuentas/**, /auth/**
          filters:
            - AuthenticationFilter

        # --- Ruta para Monopatin MS ---
        - id: monopatin-ms
          uri: http://localhost:8006
          predicates:
            - Path=/monopatines/**
          filters:
            - AuthenticationFilter

        # --- Ruta para Parada MS ---
        - id: parada-ms
          uri: http://localhost:8005
          predicates:
            - Path=/paradas/**
          filters:
            - AuthenticationFilter

        # --- Ruta para Tarifa MS ---
        - id: tarifa-ms
          uri: http://localhost:8004
          predicates:
            - Path=/tarifas/**
          filters:
            - AuthenticationFilter

        # --- Ruta para Viaje MS ---
        - id: viaje-ms
          uri: http://localhost:8007
          predicates:
            - Path=/viajes/**
          filters:
            - AuthenticationFilter

        # --- Ruta para Facturacion MS ---
        - id: factura-ms
          uri: http://localhost:8003
          predicates:
            - Path=/facturas/**
          filters:
            - AuthenticationFilter